#Imagem base
FROM openjdk:8-jdk-alpine

#Informacoes sobre a imagem
LABEL autor="Rebeca Dantas, Paulo Emílio, Lilían Lucena, Vinicius" \
      email="rebeca.queiroz@dce.ufpb.br" \
      data_criacao="18/05/2019" \
      versao="1.0.0" \
      descricao="Especifica a imagem Docker do Ispotifay" \
      licenca="copyright"

#Iniciando o servico ao iniciar o conteiner
ENTRYPOINT ["/bin/bash", "-c", "/run.sh $APP_PROFILE"]
